sonar.organization=kalinom7
sonar.projectKey=kalinom7_workouter
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/integration/lcov.info,coverage/e2e/lcov.info