name: CI Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pipeline:
    name: Build, test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: 'npm ci'

      - name: Build app
        run: 'npm run build'

      - name: Run lint checks
        run: 'npm run lint'

      - name: Run unit tests
        run: 'npm run test:unit'

      - name: Run integration tests
        run: 'npm run test:integration'

      - name: Run e2e tests
        run: 'npm run test:e2e'

      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
